name: flutter_player
description: A new Flutter project.

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  fijkplayer: ^0.11.0
  media_kit: ^1.1.10+1                        
  media_kit_video: ^1.2.4                        
  media_kit_libs_video: ^1.0.4    
  video_player: ^2.8.2
  flutter_vlc_player: ^7.4.1             

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true